// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7_hpjIwLbKpONSEEJuh-6ocB0rV5pQAI',
    appId: '1:192015845542:web:d8f80bc30194cf11aa4c67',
    messagingSenderId: '192015845542',
    projectId: 'chat-app-eb6c1',
    authDomain: 'chat-app-eb6c1.firebaseapp.com',
    storageBucket: 'chat-app-eb6c1.appspot.com',
    measurementId: 'G-V9415LFGS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvEUqAk6ff6wFDT2INfuoEO3FU68-K9Wg',
    appId: '1:192015845542:android:8eb56520c702cd6baa4c67',
    messagingSenderId: '192015845542',
    projectId: 'chat-app-eb6c1',
    storageBucket: 'chat-app-eb6c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnVUJMwlKOBACFtk78hWnVSB-WU6SioZI',
    appId: '1:192015845542:ios:c5b12a7e34773d36aa4c67',
    messagingSenderId: '192015845542',
    projectId: 'chat-app-eb6c1',
    storageBucket: 'chat-app-eb6c1.appspot.com',
    iosClientId: '192015845542-jhpv5bmce8ndbgosjic7eacpmongmcgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppAf12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnVUJMwlKOBACFtk78hWnVSB-WU6SioZI',
    appId: '1:192015845542:ios:ae2c9425f72910c2aa4c67',
    messagingSenderId: '192015845542',
    projectId: 'chat-app-eb6c1',
    storageBucket: 'chat-app-eb6c1.appspot.com',
    iosClientId: '192015845542-lkpum9gql61g1kcll1iu6utcon5qrlov.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppAf12.RunnerTests',
  );
}
